# Generated by Django 3.2.22 on 2023-12-05 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='watchlist',
            field=models.ManyToManyField(blank='true', related_name='tbr', to=settings.AUTH_USER_MODEL),
        ),
    ]
